#pragma once

#define ORCA_MOUSE_BUTTON_1         0
#define ORCA_MOUSE_BUTTON_2         1
#define ORCA_MOUSE_BUTTON_3         2
#define ORCA_MOUSE_BUTTON_4         3
#define ORCA_MOUSE_BUTTON_5         4
#define ORCA_MOUSE_BUTTON_6         5
#define ORCA_MOUSE_BUTTON_7         6
#define ORCA_MOUSE_BUTTON_8         7
#define ORCA_MOUSE_BUTTON_LAST      ORCA_MOUSE_BUTTON_8
#define ORCA_MOUSE_BUTTON_LEFT      ORCA_MOUSE_BUTTON_1
#define ORCA_MOUSE_BUTTON_RIGHT     ORCA_MOUSE_BUTTON_2
#define ORCA_MOUSE_BUTTON_MIDDLE    ORCA_MOUSE_BUTTON_3